# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Becky Tarbotton Memorial Scholarship
email: info@dbeckytarbottonscholarship.org
description: Supporting leadership and commitment in the fields of environmental and social justice
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beckytarbottonscholarship.org" # the base hostname & protocol for your site
twitter_username: beckyscholar
github_username:  tsunamiCam
fb_admins: "https://www.facebook.com/cameron.tarbotton"
fb_appid: 1707383322824946


# Build settings
markdown: kramdown


gems:
  - jekyll-sitemap